[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install --frozen-lockfile && pnpm --filter @profesional/contracts build && pnpm --filter @profesional/web build"

[deploy]
startCommand = "cd apps/web && pnpm start"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NODE_ENV = "production"
