[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "echo 'Building workspace with Turbo...'",
  "pnpm turbo build --filter=@profesional/api... --filter=@profesional/web..."
]

[start]
cmd = "cd apps/api && pnpm start"

[variables]
NODE_ENV = "production"
PNPM_VERSION = "8.15.6"
