[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "echo 'Building packages first...'",
  "pnpm --filter @profesional/contracts build",
  "pnpm --filter @profesional/ui build",
  "echo 'Building applications...'",
  "pnpm --filter @profesional/api build",
  "pnpm --filter @profesional/web build"
]

[start]
cmd = "cd apps/api && pnpm start"

[variables]
NODE_ENV = "production"
PNPM_VERSION = "8.15.6"
