[build]
builder = "nixpacks"
buildCommand = "cd ../.. && pnpm install && pnpm build --filter=api"

[deploy]
startCommand = "cd apps/api && pnpm start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[environment]
NODE_ENV = "production"

[services]
redis = "redis"
postgres = "postgresql"
